---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet restore
  - dotnet build ./AlpheusCore/
  - dotnet build ./Alpheus.CLI/
  - dotnet build ./AlpheusUnitTests
  - dotnet test ./AlpheusUnitTests
- name: build & publish release
  image: mcr.microsoft.com/dotnet/sdk:6.0
  environment:
    NUGETTOKEN:
      from_secret: nuget_angaraproject_token
  when:
    event:
    - tag
  commands:
  - dotnet build -c Release Alpheus.CLI
  - dotnet pack -c Release -p:PackageVersion=${DRONE_TAG} Alpheus.CLI
  - dotnet nuget push -k $NUGETTOKEN -s https://api.nuget.org/v3/index.json Alpheus.CLI/bin/Release/Alpheus-cli.${DRONE_TAG}.nupkg
---
kind: signature
hmac: 5e9e33f935cc215dd320c559bbeb8c731da4d8cc6dcd2c98360386d714aebbf0

...
