coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false
       